##############################
# Apollo Project             #
# Test Harness Makefile      #
# (c) 2022 Apollo Developers #
##############################

obj_$(CONFIG_TESTING) := ../third_party/unity/unity_fixture.c ../third_party/unity/unity.c
obj_$(CONFIG_TESTING) += testing.c