##############################
# Apollo Project             #
# Clock Driver Makefile      #
# (c) 2022 Apollo Developers #
##############################

obj_$(CONFIG_CLOCK_RTC_CMOS) += rtc-cmos.c
obj_$(CONFIG_CLOCK_8254) += i8254.c

test_$(CONFIG_CLOCK_8254) += i8254_test.c
