##############################
# Apollo Project             #
# Serial TTY Driver Makefile #
# (c) 2022 Apollo Developers #
##############################

obj_$(CONFIG_CONSOLE_SERIAL_16550_UART) += 16550_uart.c
#obj_$(CONFIG_CONSOLE_SERIAL_RPI4_UART) += rpi4_uart.c
