##############################
# Apollo Project             #
# Serial TTY Driver Makefile #
# (c) 2022 Apollo Developers #
##############################

obj_$(CONFIG_TTY_SERIAL_16550_UART) += 16550_uart.c
