###################################
# Apollo Project                  #
# x86 HAL Implementation Makefile #
# (c) 2022 Apollo Developers      #
###################################
ifeq ($(CONFIG_TARGET), "x86")

obj_$(CONFIG_TIMEKEEPING) += timekeeping.c
obj_$(CONFIG_CONSOLE) += console.c

endif
