####################################
# Apollo Project                   #
# rpi4 HAL Implementation Makefile #
# (c) 2022 Apollo Developers       #
####################################
ifeq ($(CONFIG_TARGET), "rpi4")

obj_$(CONFIG_CONSOLE) += console.c

endif
