##############################
# Apollo Project             #
# libc Makefile              #
# (c) 2022 Apollo Developers #
##############################
obj_$(CONFIG_LIBC_MATH) += math.c
obj_$(CONFIG_LIBC_STDIO) += stdio.c
obj_$(CONFIG_LIBC_STRING) += string.c