##############################
# Apollo Project             #
# Base Drivers Makefile      #
# (c) 2022 Apollo Developers #
##############################

# qemu shutdown hack for the qemu emulator
obj_$(CONFIG_QEMU_SHUTDOWN) += qemu_shutdown.c
