####################################
# Apollo Project                   #
# Raspberry Pi 4 specific Makefile #
# (c) 2022 Apollo Developers       #
####################################

obj_$(CONFIG_RPI4_BASE) := boot.S 
obj_$(CONFIG_RPI4_BASE) += bringup.c
