##############################
# Apollo Project             #
# Console Driver Makefile    #
# (c) 2022 Apollo Developers #
##############################

# Hosted local console
obj_$(CONFIG_CONSOLE_HOSTED) += hosted_console.c

# Basic VGA Console
obj_$(CONFIG_CONSOLE_VGA) += vga_console.c
