##############################
# Apollo Project             #
# Core Code Makefile         #
# (c) 2022 Apollo Developers #
##############################

obj_y = hal.c main.c kmain.c
obj_y += locking.c
obj_y += early_pmm.c resource.c devices.c
