##############################
# Apollo Project             #
# Core Code Makefile         #
# (c) 2022 Apollo Developers #
##############################

obj_y = hal.c main.c kmain.c early_pmm.c 
obj_y += irqchip.c resource.c devices.c
