###############################
# Apollo Project              #
# Framebuffer Driver Makefile #
# (c) 2022 Apollo Developers  #
###############################

# VGA Display Driver
obj_$(CONFIG_FRAMEBUFFER_VGA) += vga.c vga_fonts.c
