##############################
# Apollo Project             #
# Display Driver Makefile    #
# (c) 2022 Apollo Developers #
##############################

# VGA Display Driver
obj_$(CONFIG_DISPLAY_VGA) += vga.c vga_fonts.c
