AS	= nasm
CC	= /usr/cross/bin/i586-elf-gcc
LD	= /usr/cross/bin/i586-elf-ld

CFLAGS	= -Wall -O -fstrength-reduce -fomit-frame-pointer -finline-functions -nostdinc -fno-builtin -I$(ROOTDIR)include
ASFLAGS	= -felf

.SUFFIXES = .c .s

$(PROG): $(OBJS)
	$(LD) -r $(OBJS) -o ../$(PROG)
.c.o:
	$(CC) $(CFLAGS) -c $< -o $@
.s.o:
	$(AS) $(ASFLAGS) $< -o $@
clean:
	rm -f *~ $(OBJS) $(PROG)
