AS	= nasm
CC	= gcc -m32 -march=i486
LD	= ld -melf_i386

CFLAGS	= -Wall -O -fno-builtin -masm=intel -fno-stack-protector -nostdlib -nostdinc -I$(ROOTDIR)include
ASFLAGS	= -felf

.SUFFIXES = .c .s

$(PROG): $(OBJS)
	$(LD) -r $(OBJS) -o ../$(PROG)
.c.o:
	$(CC) $(CFLAGS) -c $< -o $@
.s.o:
	$(AS) $(ASFLAGS) $< -o $@
clean:
	rm -f *~ $(OBJS) $(PROG) */*.o
