##############################
# Apollo Project             #
# IRQ Driver Makefile        #
# (c) 2022 Apollo Developers #
##############################

obj_$(CONFIG_IRQ) += irqchip.c
obj_$(CONFIG_IRQCHIP_8259) += 8259_pic.c
